### ISSUE TITLE
Bug: Release action runs a script from non existing file

### ISSUE THREAD

**Issue by RayRedGoose** [Workday/canvas-kit-actions#14]
`utils/update-changelog.js` is existing in CK, so that's why we don't have any failure, but this step should be more dynamic

```yml
## We could have gone the route of a lerna changeset plugin, but we would lose access to
    ## usernames which add a nice human touch to release notes
    - name: Update Changelog
      shell: bash
      run: node utils/update-changelog.js
      env:
        CHANGESET_TITLE: ${{steps.changeset.outputs.title}}
        CHANGESET_BODY: |
          ${{steps.changeset.outputs.body}}
```
